#-*- mode: makefile; tab-width: 4; -*-
# $FreeBSD$

PORTNAME=				%%PORTNAME%%
PORTVERSION=			%%PORTVERSION%%
CATEGORIES=				%%CATEGORY%% xepkgs

MAINTAINER=				xemacs@FreeBSD.org
COMMENT=				%%COMMENT%%

LICENSE=				GPLv2

RUN_DEPENDS=			%%RUN_DEPENDS%%

USE_XEPKGS=				yes

.include <bsd.port.mk>
