FILES=		backup.inc \
		common.inc \
		common.inc.rb \
		html.inc.rb \
		latex.inc.rb \
		mail.inc \
		ports.inc \
		sdoc.inc.rb \
		sys.inc
DESTDIR?=	${LOCALBASE}/opentools
FILESDIR=	/include

install: installfiles

.include <bsd.init.mk>
.include <bsd.files.mk>
